"""Export Word documents to ACB-compliant HTML.

Two output modes:
1. CMS fragment -- body-only HTML with embedded CSS (copy-paste into
   WordPress, Drupal, or any CMS WYSIWYG / HTML block).
2. Standalone HTML -- full document shell with external CSS file,
   ready for browser viewing, email, or file distribution.

Uses mammoth for docx-to-HTML conversion, then post-processes the
output to enforce ACB Large Print Guidelines.
"""

from __future__ import annotations

import re
from html import escape
from pathlib import Path

import mammoth

from . import __version__

# ---------------------------------------------------------------------------
# ACB CSS (embedded as a Python constant to keep the tool self-contained)
# ---------------------------------------------------------------------------

ACB_CSS = """\
/* ACB Large Print Guidelines CSS -- generated by ACB Large Print Tool */
html { font-size: 100%; }
body {
  font-family: Arial, sans-serif;
  font-size: 1.5rem;
  font-weight: 400;
  color: #1a1a1a;
  background-color: #ffffff;
  text-align: left;
  line-height: 1.5;
  letter-spacing: 0.12em;
  word-spacing: 0.16em;
  margin: 0 auto;
  padding: 1rem 1rem;
  max-width: 70ch;
  hyphens: none;
  -webkit-hyphens: none;
  columns: 1;
}
h1, h2 {
  font-family: Arial, sans-serif;
  font-size: 1.833rem;
  font-weight: 700;
  line-height: 1.5;
  text-align: left;
  text-transform: none;
  margin-top: 1.5em;
  margin-bottom: 1em;
}
h3, h4, h5, h6 {
  font-family: Arial, sans-serif;
  font-size: 1.667rem;
  font-weight: 700;
  line-height: 1.5;
  text-align: left;
  text-transform: none;
  margin-top: 1.5em;
  margin-bottom: 1em;
}
p {
  margin-top: 0;
  margin-bottom: 2em;
}
em, .acb-emphasis {
  font-style: normal;
  text-decoration: underline;
  text-decoration-thickness: 2px;
  text-underline-offset: 3px;
}
u {
  text-decoration: underline;
  text-decoration-thickness: 2px;
  text-underline-offset: 3px;
}
strong { font-weight: 700; }
a {
  color: #0055cc;
  text-decoration: underline;
  text-decoration-thickness: 1px;
}
a:hover, a:focus {
  text-decoration-thickness: 2px;
  outline: 2px solid currentColor;
  outline-offset: 2px;
}
ul {
  list-style-type: disc;
  padding-left: 1.5em;
  margin-top: 0;
  margin-bottom: 2em;
}
ul li { margin-bottom: 0; padding-left: 0.5em; font-size: inherit; }
ul li::marker { color: #1a1a1a; font-size: 1.2em; }
ol {
  list-style-type: decimal;
  padding-left: 1.5em;
  margin-top: 0;
  margin-bottom: 2em;
}
ol li { margin-bottom: 0; padding-left: 0.5em; font-size: inherit; }
table {
  border-collapse: collapse;
  width: 100%;
  font-size: inherit;
}
th, td {
  text-align: left;
  padding: 0.5em 0.75em;
  border: 1px solid #666;
}
th { font-weight: 700; }
caption {
  font-family: Arial, sans-serif;
  font-size: 1.5rem;
  font-weight: 700;
  text-align: left;
  margin-bottom: 0.5em;
}
figure { margin: 1.5em 0; }
figcaption { font-family: Arial, sans-serif; font-size: 1.5rem; margin-top: 0.5em; }
img { max-width: 100%; height: auto; }
p, li { orphans: 3; widows: 3; }
@media print {
  body {
    line-height: 1.15;
    color: #000000;
    background-color: #faf8f0;
    max-width: none;
    padding: 0;
  }
  @page { margin: 1in; }
  @page :left { margin-left: 1.5in; }
  a { color: #000000; text-decoration: underline; }
}
"""


# ---------------------------------------------------------------------------
# Mammoth style mapping for ACB output
# ---------------------------------------------------------------------------

_MAMMOTH_STYLE_MAP = """
p[style-name='Heading 1'] => h1:fresh
p[style-name='Heading 2'] => h2:fresh
p[style-name='Heading 3'] => h3:fresh
p[style-name='Heading 4'] => h4:fresh
p[style-name='Heading 5'] => h5:fresh
p[style-name='Heading 6'] => h6:fresh
p[style-name='List Bullet'] => ul > li:fresh
p[style-name='List Number'] => ol > li:fresh
p[style-name='List Paragraph'] => ul > li:fresh
r[style-name='Strong'] => strong
r[style-name='Emphasis'] => em
r[style-name='Intense Emphasis'] => em
b => strong
i => em
u => u
""".strip()


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------


def _post_process_html(html: str) -> str:
    """Clean up mammoth output for ACB compliance."""
    # mammoth emits <em> for italic -- ACB says no italic, convert to underline
    # The CSS already sets em { font-style: normal; text-decoration: underline }
    # so the markup is fine, but strip any inline style attributes mammoth adds
    html = re.sub(r'<em style="[^"]*">', "<em>", html)

    # Remove empty paragraphs
    html = re.sub(r"<p>\s*</p>", "", html)

    # Ensure tables have scope attributes on th elements
    html = re.sub(
        r"<th(?!\s+scope=)",
        '<th scope="col"',
        html,
    )

    # Strip any style attributes that mammoth embeds (we use CSS classes)
    html = re.sub(r'\s+style="[^"]*"', "", html)

    return html.strip()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def convert_docx_to_html(docx_path: str | Path) -> tuple[str, list[str]]:
    """Convert a .docx file to ACB-compliant HTML body content.

    Returns:
        Tuple of (html_body_content, warnings_list).
    """
    docx_path = Path(docx_path)

    with open(docx_path, "rb") as f:
        result = mammoth.convert_to_html(
            f,
            style_map=_MAMMOTH_STYLE_MAP,
        )

    body_html = _post_process_html(result.value)
    warnings = [str(w) for w in result.messages if w.type == "warning"]

    return body_html, warnings


def export_cms_fragment(
    docx_path: str | Path,
    output_path: str | Path,
    *,
    title: str = "",
) -> tuple[Path, list[str]]:
    """Export a CMS-ready HTML fragment with embedded CSS.

    Output is a single HTML file with <style> block -- ready to paste
    into WordPress, Drupal, or any CMS HTML block editor.

    Args:
        docx_path: Input .docx file.
        output_path: Where to save the HTML fragment.
        title: Optional document title shown as heading.

    Returns:
        Tuple of (output_path, warnings).
    """
    body_html, warnings = convert_docx_to_html(docx_path)
    output_path = Path(output_path)

    # CMS fragment: style block + content, no doctype/html/head/body shell
    parts: list[str] = []
    parts.append(f"<style>\n{ACB_CSS}</style>")
    parts.append("")
    parts.append('<div class="acb-large-print">')
    if title:
        parts.append(f"  <h1>{escape(title)}</h1>")
    parts.append(f"  {body_html}")
    parts.append("</div>")
    parts.append(f"<!-- Generated by ACB Large Print Tool v{__version__} -->")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts), encoding="utf-8")

    return output_path, warnings


def export_standalone_html(
    docx_path: str | Path,
    output_path: str | Path,
    *,
    title: str = "",
    css_path: str | Path | None = None,
) -> tuple[Path, Path, list[str]]:
    """Export a full standalone HTML document with separate CSS file.

    Creates both the HTML file and a companion acb-large-print.css file
    in the same directory.

    Args:
        docx_path: Input .docx file.
        output_path: Where to save the HTML file.
        title: Document title for <title> and <h1>.
        css_path: Custom CSS file path. If None, generates one alongside.

    Returns:
        Tuple of (html_path, css_path, warnings).
    """
    body_html, warnings = convert_docx_to_html(docx_path)
    output_path = Path(output_path)

    # Write CSS file alongside the HTML
    if css_path is None:
        css_path = output_path.parent / "acb-large-print.css"
    css_path = Path(css_path)
    css_path.parent.mkdir(parents=True, exist_ok=True)
    css_path.write_text(ACB_CSS, encoding="utf-8")

    # Compute relative path from HTML to CSS
    try:
        css_rel = css_path.relative_to(output_path.parent)
    except ValueError:
        css_rel = css_path

    doc_title = escape(title) if title else "ACB Large Print Document"

    html = f"""\
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{doc_title}</title>
  <link rel="stylesheet" href="{css_rel}">
</head>
<body>
  <main>
    <h1>{doc_title}</h1>
    {body_html}
  </main>
  <!-- Generated by ACB Large Print Tool v{__version__} -->
</body>
</html>
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")

    return output_path, css_path, warnings
