#!/usr/bin/env python3
"""Build pre-rendered HTML partials from source Markdown files.

This script is the single document builder for web-facing long-form docs.
It converts source Markdown into committed HTML partials so the Flask app
serves static template includes instead of parsing Markdown at runtime.

Generated files:
- web/src/acb_large_print_web/templates/partials/guide_body.html
- web/src/acb_large_print_web/templates/partials/changelog_body.html
- web/src/acb_large_print_web/templates/partials/prd_body.html
- web/src/acb_large_print_web/templates/partials/faq_body.html

Usage:
    python scripts/build-doc-pages.py
    python scripts/build-doc-pages.py guide faq
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PARTIALS_DIR = (
    REPO_ROOT
    / "web"
    / "src"
    / "acb_large_print_web"
    / "templates"
    / "partials"
)

# name -> (source_md, output_partial, options)
# options keys:
# - toc_heading: heading text for nav section, or None to skip nav
# - toc_id: id for nav heading and back-to-top anchor
# - body_class: wrapper class around converted body html
# - back_label: back-to-top label text, or None to skip back link
SOURCES: dict[str, tuple[Path, Path, dict[str, str | None]]] = {
    "guide": (
        REPO_ROOT / "docs" / "user-guide.md",
        PARTIALS_DIR / "guide_body.html",
        {
            "toc_heading": "In This Guide",
            "toc_id": "guide-toc-heading",
            "body_class": "guide-content",
            "back_label": "Back to guide contents",
        },
    ),
    "changelog": (
        REPO_ROOT / "CHANGELOG.md",
        PARTIALS_DIR / "changelog_body.html",
        {
            "toc_heading": "Versions",
            "toc_id": "changelog-toc-heading",
            "body_class": "changelog-content",
            "back_label": "Back to version list",
        },
    ),
    "prd": (
        REPO_ROOT / "docs" / "prd.md",
        PARTIALS_DIR / "prd_body.html",
        {
            "toc_heading": "Sections",
            "toc_id": "prd-toc-heading",
            "body_class": "prd-content",
            "back_label": "Back to sections",
        },
    ),
    "faq": (
        REPO_ROOT / "docs" / "faq.md",
        PARTIALS_DIR / "faq_body.html",
        {
            "toc_heading": None,
            "toc_id": None,
            "body_class": "faq-content",
            "back_label": None,
        },
    ),
}

def _escape_jinja(html: str) -> str:
    """Escape brace sequences that Jinja2 would interpret as directives or variables.

    After markdown-to-HTML conversion, code examples in the source may contain
    Jinja-like syntax (e.g. ``{{.Name}}``, ``{% if %}``, ``{{ }}``).  Replacing
    those sequences with HTML entities makes the output safe to include inside a
    Jinja template without a ``{% raw %}`` block -- which is itself fragile because
    any changelog entry that *documents* ``{% endraw %}`` would prematurely close
    a raw block and re-expose later content to the parser.
    """
    html = html.replace("{{", "&#123;&#123;")
    html = html.replace("{%", "&#123;%")
    html = html.replace("%}", "%&#125;")
    return html


BANNER = (
    "<!-- AUTO-GENERATED by scripts/build-doc-pages.py -- DO NOT EDIT MANUALLY -->\n"
    "<!-- Source: {source} -->\n"
    "<!-- Run `python scripts/build-doc-pages.py` to regenerate -->\n\n"
)


def _slugify(value: str, separator: str = "-") -> str:
    slug = re.sub(r"[^\w\s-]", "", value.lower())
    return re.sub(r"[\s_]+", separator, slug.strip())


def _convert_md(md_text: str) -> tuple[str, str]:
    """Return (toc_html, body_html) from markdown text."""
    import markdown

    md = markdown.Markdown(
        extensions=["toc", "tables", "fenced_code", "attr_list", "nl2br", "md_in_html"],
        extension_configs={
            "toc": {
                "permalink": False,
                "slugify": _slugify,
            }
        },
    )
    body_html = md.convert(md_text)
    toc_html = md.toc or ""
    return toc_html, body_html


def build(name: str) -> bool:
    src_path, out_path, options = SOURCES[name]

    if not src_path.exists():
        print(f"  [SKIP] {name}: source not found ({src_path})", file=sys.stderr)
        return False

    md_text = src_path.read_text(encoding="utf-8")
    toc_html, body_html = _convert_md(md_text)
    toc_html = _escape_jinja(toc_html)
    body_html = _escape_jinja(body_html)

    parts: list[str] = []

    toc_heading = options.get("toc_heading")
    toc_id = options.get("toc_id")
    if toc_heading and toc_id and toc_html.strip():
        parts.append(
            f'<nav aria-labelledby="{toc_id}">\n'
            f'  <h2 id="{toc_id}">{toc_heading}</h2>\n'
            f'{toc_html}\n'
            f'</nav>'
        )

    body_class = options.get("body_class") or "doc-content"
    parts.append(f'<div class="{body_class}">\n{body_html}\n</div>')

    back_label = options.get("back_label")
    if back_label and toc_id:
        parts.append(f'<a href="#{toc_id}" class="back-to-top">{back_label}</a>')

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # No {% raw %} wrapper needed: all Jinja-like sequences ({{, {%, %}) are
    # already replaced with HTML entities by _escape_jinja() above.
    body = "\n".join(parts)
    out_path.write_text(
        BANNER.format(source=src_path.relative_to(REPO_ROOT)) + body + "\n",
        encoding="utf-8",
    )

    print(
        f"  [OK]   {name}: {src_path.relative_to(REPO_ROOT)} -> {out_path.relative_to(REPO_ROOT)}"
    )
    return True


def main() -> int:
    targets = sys.argv[1:] if len(sys.argv) > 1 else list(SOURCES)

    unknown = [t for t in targets if t not in SOURCES]
    if unknown:
        print(f"Unknown targets: {', '.join(unknown)}", file=sys.stderr)
        print(f"Valid targets: {', '.join(SOURCES)}", file=sys.stderr)
        return 1

    PARTIALS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Building doc partials: {', '.join(targets)}")

    ok = all(build(name) for name in targets)
    print("Done." if ok else "Some targets failed -- see messages above.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
